version: "3"
services:
  notebook:
    container_name: notebook
    image: jupyter/datascience-notebook
    environment:
      CHOWN_HOME: "yes"
      JUPYTER_ENABLE_LAB: "yes"
      TZ: Europe/Warsaw
    volumes:
      - data:/home/jovyan/
    restart: unless-stopped
    labels:
      - traefik.enable=true
    networks:
      - traefik
    command: start-notebook.sh --NotebookApp.password=${PW_HASH}

volumes:
  data:

networks:
  traefik:
    external: true
