version: '3.3'
services:
  ipsec-vpn-server:
    container_name: ipsec-vpn
    image: hwdsl2/ipsec-vpn-server
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    restart: unless-stopped
    environment:
      - VPN_IPSEC_PSK=${VPN_IPSEC_PSK}
      - VPN_USER=${VPN_USER}
      - VPN_PASSWORD=${VPN_PASSWORD}
