version: "3.3"

services:
  whoami:
    image: containous/whoami
    container_name: whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=HostRegexp(`whoami.{domain:[a-z0-9.]+}`)
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
