version: "3.1"
services:
  audiobookshelf:
    container_name: audiobookshelf
    image: advplyr/audiobookshelf:latest
    restart: unless-stopped
    labels:
      - traefik.enable=true
    networks:
      - traefik
    volumes:
      - config:/config
      - metadata:/metadata
      - ~/data/audiobooki:/audiobooks

networks:
  traefik:
    external: true

volumes:
  config:
  metadata:
