version: "2.1"

services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - data:/config
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.heimdall.rule=Host(`${DOMAINNAME}`)


volumes:
  data:

networks:
  traefik:
    external: true
