version: "3.3"

services:
  lmap:
    container_name: lmap
    image: allgreed/lmap
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.lmap.rule=HostRegexp(`lmap.{domain:[a-z0-9.]+}`)

networks:
  traefik:
    external: true
