version: "3.3"

services:
  lmap:
    container_name: lmap
    image: allgreed/lmap
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true

networks:
  traefik:
    external: true
