version: "2.1"

services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    ports:
      - 6881:6881
      - 6881:6881/udp
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Warsaw
    volumes:
      - config:/config
      - ~/data:/downloads
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8080
    networks:
      - traefik

volumes:
  config:

networks:
  traefik:
    external: true
