version: "2.1"

services:
  emby:
    image: linuxserver/emby
    container_name: emby
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Warsaw
    volumes:
      - data:/config
      - ~/data:/data
    restart: unless-stopped
    labels:
      - traefik.enable=true
    networks:
      - traefik

volumes:
  data:

networks:
  traefik:
    external: true
