version: "2"
services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
      - "25826:25826/udp"
    volumes:
      - influxdb:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./types.db:/usr/share/collectd/types.db:ro
    environment:
      - INFLUXDB_DB=collectd
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    image: grafana/grafana
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=HostRegexp(`grafana.{domain:[a-z]+}.{tld:[a-z]+}`)
volumes:
  influxdb:
  grafana:
