version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      TZ: Europe/Warsaw
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
      - data:/etc/pihole/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=HostRegexp(`pihole.{domain:[a-z0-9.]+}`)
      - traefik.http.services.pihole.loadbalancer.server.port=80
    networks:
      - traefik

networks:
  traefik:
    external: true

volumes:
  data:
