version: '3'

services:
  ftp:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "~/data/webcams:/webcams"
    environment:
      PUBLICHOST: "tygrys.me"
      FTP_USER_NAME: yicam
      FTP_USER_PASS: UbuuDUJQuMNvvGrUcEkN
      FTP_USER_HOME: /webcams
    restart: unless-stopped

