version: "3"

services:
  ouroboros:
    container_name: ouroboros
    image: pyouroboros/ouroboros
    environment:
      CLEANUP: "true"
      INTERVAL: 60
      LOG_LEVEL: info
      SELF_UPDATE: "true"
      TZ: Europe/Warsaw
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
