version: "3"

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 120
    dns:
      - 1.1.1.1
    restart: unless-stopped
