version: "2"

services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:edge
    volumes:
      - work:/opt/adguardhome/work
      - conf:/opt/adguardhome/conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 853:853/tcp
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.adguard.loadbalancer.server.port=80
    networks:
      - traefik

volumes:
  work:
  conf:

networks:
  traefik:
    external: true
