version: "3.3"
services:
  docker-instaloader:
    container_name: instaloader
    volumes:
      - "~/instaloader:/download"
      - "./args.txt:/il_args.txt"
      - "./targets.txt:/il_targets.txt"
    image: didc/docker-instaloader
