version: "3.3"

services:
  instaloader:
    container_name: instaloader
    image: didc/docker-instaloader
    environment:
      TZ: Europe/Warsaw
    volumes:
      - ~/instaloader:/download
      - ./args.txt:/il_args.txt
      - ./targets.txt:/il_targets.txt