version: "3"

services:
  rclone: 
    image: rclone/rclone:beta
    container_name: rclone
    volumes:
      - ~/.config/rclone:/config/rclone
      - ~/data:/data:shared
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
    command: "mount data: /data \
    --allow-other \
    --transfers 1 \
    --no-modtime \
    --async-read=true \
    --buffer-size 512M \
    --fast-list \
    --timeout 30m \
    --dir-cache-time 6h \
    --drive-chunk-size 64M \
    --vfs-cache-max-age 72h \
    --vfs-cache-mode off \
    --vfs-cache-max-size 40G \
    --vfs-read-chunk-size 4M \
    --vfs-read-chunk-size-limit 1G \
    --stats 1m \
    --stats-one-line \
    --log-level=INFO"
