version: "3"

services:
  rclone: 
    image: rclone/rclone:beta
    container_name: rclone
    volumes:
      - ~/.config/rclone:/config/rclone
      - ~/data:/data:shared
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
    command: "mount data: /data \
    --allow-other \
    --allow-non-empty \
    --no-modtime \
    --buffer-size 4M \
    --timeout 30m \
    --dir-cache-time 6h \
    --vfs-cache-max-age 72h \
    --vfs-cache-mode full \
    --vfs-cache-max-size 10G \
    --vfs-read-chunk-size 4M \
    --vfs-read-chunk-size-limit 1G \
    --vfs-write-back 1m \
    --stats 10s \
    --stats-one-line \
    --log-level=INFO"
