version: "3.7"

services:
  rclone: &template
    image: rclone/rclone:beta
    container_name: rclone
    volumes:
      - ~/.config/rclone:/config/rclone
      - ~/data:/data:shared
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
    command: "mount s1:seriale /data/seriale --allow-other --gid 1001 --uid 1001"
  rclone2:
    <<: *template
    container_name: rclone2
    command: "mount s2:cassad /data/filmy --allow-other --gid 1001 --uid 1001"
