version: "3.3"

services:
  nginx:
    container_name: nginx
    image: nginxdemos/hello
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true

networks:
  traefik:
    external: true
