version: "2.1"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Warsaw
      - JELLYFIN_CONFIG_DIR=/config
      - JELLYFIN_DATA_DIR=/config/data
      - JELLYFIN_LOG_DIR=/config/log
      - JELLYFIN_CACHE_DIR=/config/cache
    volumes:
      - config:/config
      - ~/data:/data:shared
      - ~/pobrane:/pobrane:shared
    restart: unless-stopped
    labels:
      - traefik.enable=true
    networks:
      - traefik

volumes:
  config:

networks:
  traefik:
    external: true
