version: "3.3"
services:
  portainer:
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    image: portainer/portainer
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=HostRegexp(`portainer.{domain:[a-z]+}.{tld:[a-z]+}`)
volumes:
  portainer_data:
networks:
  traefik:
    external: true
