version: "3.3"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    networks:
      - traefik
    labels:
      - traefik.enable=true

volumes:
  data:

networks:
  traefik:
    external: true
